#+title: Font Notes
* Installing fonts
** Mac OS
Use the Font Book app.
** Linux (including Crostini on Chrome OS)
#+begin_example
cp some-font.ttf another-font.ttc ~/.fonts/
fc-cache -fv
#+end_example
* Bitmap (and bitmap-derived) fonts
More useful for lower DPI screens.
** Dina
Great monospaced bitmap font for coding ([[https://www.dcmembers.com/jibsen/download/61/][link]]).
A third-party remastered TTF version is also available ([[https://github.com/zshoals/Dina-Font-TTF-Remastered][link]]).
The TTF font was created at 10pt size, but is still reasonable to use at 16pt.
** Greybeard (remastered UW ttyp0 fonts)
This is the [[https://people.mpi-inf.mpg.de/~uwe/misc/uw-ttyp0/][UW ttyp0]] monospaced bitmap font compiled using alternate glyphs ([[https://github.com/flowchartsman/greybeard][link]]).
It has bitmap strikes in the following pixel sizes: 11, 12, 13, 14, 15, 16, 17, 18 and 22.
Each of these has a bold variant, and italic variants are provided in 15, 16, 17 and 18.
This is a little thin to be used effectively in HiDPI systems, but it has very good unicode coverage and works well as a fallback font.
** Pixel Operator
Variable and monospaced bitmap font ([[https://notabug.org/HarvettFox96/ttf-pixeloperator][link]]).
Good alternative to Dina.
The variable version wells work together with Dina.
Also works great at 16pt size.
** ProFontIIx Nerd Font Mono
[[https://www.nerdfonts.com/][Nerd Fonts]] ([[https://github.com/ryanoasis/nerd-fonts][Github]]) build of [[http://tobiasjung.name/profont/][ProFont]], patched to add a lot of icon glyphs from [[https://github.com/FortAwesome/Font-Awesome][Font Awesome]], [[http://vorillaz.github.io/devicons/][Devicons]], [[https://github.com/github/octicons][Octicons]] and others.
** GNU Unifont
Unicode bitmap font with enormous glyph coverage ([[http://unifoundry.com/unifont/index.html][link]]). It is fairly lightweight (about 12 megabytes) for a font with very large coverage, and is most useful for debugging Unicode issues.
* Outline fonts
Tends to work better for high DPI screens.
** 3270
Font derived from and similar to the IBM 3270 font but in a modern format and with more characters ([[https://github.com/rbanffy/3270font][Github]]).
On Debian systems, this is available as the ~fonts-3270~ package installable via APT.
** Aileron
Neo-grotesque sans-serif font ([[http://dotcolon.net/font/aileron/][link]]).
Similar to Helvetica but ~l~ is distinct from ~I~.
** APL385
Public domain fonts designed for use with APL ([[https://www.apl385.com/fonts/index.htm][link]]).
APL385 Unicode is the monospaced version of the font and APL333 Unicode is the proportional version of the font.
There is also a font APL386 ([[https://abrudz.github.io/APL386/][link]], [[https://github.com/abrudz/APL386][Github]]) that is expands on AP385 with more characters.
Note that these fonts do not come with italics.
** Alegreya
Font family with sans-serif ([[https://www.huertatipografica.com/en/fonts/alegreya-sans-ht][link]], [[https://github.com/huertatipografica/Alegreya-Sans][Github]]) and serif ([[https://www.huertatipografica.com/en/fonts/alegreya-ht-pro][link]], [[https://github.com/huertatipografica/Alegreya][Github]]) variants designed for long-form text.
** Alma Mono
Monospaced font with multiple weights, no italics ([[http://almamono.com/][link]]).
Free for personal use.
** B612
Font released by Airbus and Intactile DESIGN ([[https://b612-font.com/][link]], [[https://github.com/polarsys/b612][Github]]).
The font uses a non-slashed zero by default ([[https://en.wikipedia.org/wiki/Symbol_(typeface)][symbol]] ~0030~), but there is also a slashed zero glyph in the private use area (unicode symbol ~E007~).
In Emacs, it is possible to change the standard display table to display slashed zeros in place of the regular non-slashed zeros by loading the following code (e.g. in the startup configuration).
#+begin_src emacs-lisp :eval no
;; the following displays '0' as '\ue007' (B612 font slashed zero)
(setq standard-display-table (make-display-table))
(aset standard-display-table ?0 [?])
#+end_src
** Bembo-like fonts
Bembo is the typeface used in Edward Tufte's books, based off well-suited for typesetting print documents.
Several digitized versions, free, commercial and proprietary, were created.
ET Book is an earlier webfont version commissioned by Edward Tufte ([[https://edwardtufte.github.io/et-book/][link]], [[https://github.com/edwardtufte/et-book][Github]]).
XETBook is expands on ET Book with added characters, OpenType ligatures and old-style figures ([[https://github.com/dbenjaminmiller/xetbook][Github]]).
ETbb further expands on XETBook to include a full set of figure styles, small caps, superior and inferior figures and LaTeX support ([[https://ctan.org/pkg/etbb?lang=en][link]]).
Currently, ETbb is preferred as it has the widest glyph coverage and the most alternate glyphs.
** Cooper Hewitt
Contemporary sans-serif, designed by Pentagram for the Cooper Hewitt Smithsonian Design Museum ([[https://www.cooperhewitt.org/open-source-at-cooper-hewitt/cooper-hewitt-the-typeface-by-chester-jenkins/][link]], [[https://github.com/cooperhewitt/cooperhewitt-typeface][Github]]).
** Courier Prime
Courier Prime, Courier Prime Sans and Courier Prime Code are a family
of fonts that are metric equivalent to Courier New and Courier Final
Draft ([[https://quoteunquoteapps.com/courierprime/][link]], [[https://github.com/quoteunquoteapps/CourierPrime][Github]]). It is designed for screenplays but the Code
variant is also a good coding font.
** DM Mono/Sans/Serif
Font families designed by Colophon Foundry for DeepMind ([[https://github.com/googlefonts/dm-mono][DM Mono link]], [[https://github.com/googlefonts/dm-fonts][DM Sans/Serif link]]).
Low contrast geometric fonts intended for use at smaller text sizes.
** Drafting Mono
Monospaced font inspired by typewriters ([[https://indestructibletype.com/Drafting/][link]], [[https://github.com/indestructible-type/Drafting][Github]]).
** Fira
Font family by Mozilla with sans-serif, serif and monospaced variants ([[http://mozilla.github.io/Fira/][link]], [[https://github.com/mozilla/Fira][Github]]).
The monospaced variant has a fork *Fira Code* ([[https://github.com/tonsky/FiraCode][Github]]) that adds ligatures and fixes line height inconsistencies with bold fonts.
** Fivo Sans
Neo-grotesque typeface ([[https://www.behance.net/gallery/53653425/Fivo-Sans-Free-Font-Family][link]]).
Has a display version Fivo Sans Modern ([[https://www.behance.net/gallery/54442585/Fivo-Sans-Modern-Free-Display-Font-Family][link]]).
** IBM Plex
IBM's open-source corporate typeface ([[https://github.com/IBM/plex][Github]]). Has monospace, sans-serif and serif families. Distinctly IBM font designed to work well in various user interface environments.
** Input
Font with monospace, sans-serif and serif families ([[https://input.fontbureau.com/][link]]).
Large x-height with many customization options available.
Free for personal use.
** Inconsolata
Open source monospace font with a wide array of weights ([[https://github.com/googlefonts/Inconsolata][link]]).
Also has a variant family Ligconsolata that exposes ligatures by default in the OpenType feature ~liga~, aimed at use in text editors.
** Inria
Proportional font family with sans-serif and serif fonts designed for Inria ([[https://black-foundry.com/work/inria/][link]], [[https://github.com/BlackFoundryCom/InriaFonts][Github]]).
** Inter
Proportional font family with sans-serif and serif fonts designed for screen usage ([[https://rsms.me/inter/][link]], [[https://github.com/rsms/inter/][Github]]).
** JuliaMono
Monospaced font designed for use with [[https://julialang.org/][Julia]] but works well as a programming font in general ([[https://cormullion.github.io/pages/2020-07-26-JuliaMono/][link]], [[https://github.com/cormullion/juliamono][Github]]).
** Iosevka
Condensed monospace typeface for code with a wide array of customization options ([[https://typeof.net/Iosevka/][link]], [[https://github.com/be5invis/Iosevka][Github]]).
The typeface also has quasi-proportional families -- Aile (Helvetica-like sans-serif), Etoile (serif) and Sparkle (mixed sans-serif and serif, with similar character spacing to Etoile).
The monospace typeface has regular and extended widths.
The extended width version can be used in Emacs by setting the face attribute ~:width~ to the symbol ~expanded~ (see following code).
One of the stylistic sets ~ss08~ tries to emulate [[https://github.com/fabrizioschiavi/pragmatapro][Pragmata Pro]], but if pairing with one of the Iosevka quasi-proportional families then it is better to use the either the default style (if pairing with Aile) or the Slab style (if pairing with Etoile).
There is also a CJK font [[https://github.com/be5invis/Sarasa-Gothic][Sarasa Gothic]] that is based on Iosevka and Source Han Sans.
#+begin_src emacs-lisp :eval no
(set-face-attribute 'default nil :family "Iosevka"
                    :height 140 :weight 'normal :width 'expanded)
#+end_src
** Latin Modern
Font extending Donald Knuth's Computer Modern fonts and a main font in LaTeX ([[http://www.gust.org.pl/projects/e-foundry/latin-modern][link]]).
Comes in text, math, monospaced and other versions.
** Literata
Serif typeface intended for long-form reading, e.g. in eBooks ([[https://github.com/googlefonts/literata][link]]).
** M+ FONTS
M+ FONTS is a Japanese sans-serif font family with good coverage for Kana and Kanji glyphs.
The 1 variant has contrasting straight lines and curves, while the 2 variant is more curvy.
The P and C variants have proportional Latin glyphs with the C variant optimized for typesetting.
The M and MN variants have monospaced half-width Latin glyphs with MN variant optimized for programming (e.g. slashed zeros).
Notes that Japanese glyphs are always monospaced full-width, and that line height for the font family is very tall.
** Merriweather
Large x-height variable serif text face designed for screen reading ([[https://github.com/EbenSorkin/Merriweather][Github]]).
** Millimetre
Geometric sans display typeface similar to Eurostile ([[https://velvetyne.fr/fonts/millimetre/][link]], [[https://gitlab.com/StudioTriple/Millimetre/][Gitlab]]).
** Noto
Massive font family by Google that aims to support all languages ([[https://www.google.com/get/noto/][link]]).
Good choice as a fallback font for esoteric languages in Emacs ([[https://idiocy.org/emacs-fonts-and-fontsets.html][link]]).
** Pragmata Pro
Commercial coding font ([[https://fsd.it/shop/fonts/pragmatapro/][link]]).
The full version can be somewhat expensive, but has very broad glyph coverage.
** Public Sans
Neutral sans-serif typeface for text or display ([[https://public-sans.digital.gov/][link]], [[https://github.com/uswds/public-sans][Github]]).
** Recursive
Monospace and Sans fonts commissioned by Google Fonts ([[https://www.recursive.design/][link]], [[https://github.com/arrowtype/recursive/][Github]]).
The ~Code~ version shifts the code ligatures from their usual OpenType feature ~dlig~ to the Opentype feature ~calt~ which makes them easier to use in code editors.
** Reforma
Typeface commissioned by the Universidad Nacional de Córdoba in Argentina ([[https://pampatype.com/reforma][link]]).
It has three subfamilies of fonts -- Reforma 1918 (serif), Reforma 2018 (sans-serif) and Reforma 1969 (an intermediate hybrid).
Interesting combinations are possible among its different styles -- the sans typeface for display use and the serif for body text, or the reverse.
** Roboto
Family of fonts commissioned by Google for Android and Chrome OS, and the recommended font for Google's Material Design visual language ([[https://github.com/googlefonts/roboto][Github]]).
** Source Code/Sans/Serif Pro
Family of fonts created by Adobe with monospaced ([[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]]), sans proportional ([[https://github.com/adobe-fonts/source-sans-pro][Source Sans Pro]]) and Serif ([[https://github.com/adobe-fonts/source-serif-pro][Source Serif Pro]]) variants.
Readable at smaller size when antialiasing is turned off.
Also has a Pan-CJK version ([[https://github.com/adobe-fonts/source-han-mono][Source Han Mono]], [[https://github.com/adobe-fonts/source-han-sans][Source Han Sans]], [[https://github.com/adobe-fonts/source-han-serif][Source Han Serif]]).
** Space Grotesk/Mono
Space Mono is a monospace font designed for Google Design ([[https://fonts.google.com/specimen/Space+Mono][link]], [[https://github.com/googlefonts/spacemono][Github]]).
Space Grotesk is a sans-serif typeface derived from Space Mono ([[https://fonts.floriankarsten.com/space-grotesk][link]], [[https://github.com/floriankarsten/space-grotesk][Github]]).
** Symbola
Font from the [[https://dn-works.com/ufas/][Unicode Fonts for Ancient Scripts]] project.
Symbola focuses on Multilingual support and Symbol blocks in [[https://unicode.org/standard/standard.html][The Unicode Standard]].
It works well as a fallback font in Emacs for when the default typeface does not have a character glyph (see following code).
For more information on configuring fonts in Emacs, see this [[https://idiocy.org/emacs-fonts-and-fontsets.html][link]].
Free for personal use.
#+begin_src emacs-lisp :eval no
;; fallback font for when the display face does not have a character glyph
(set-fontset-font t nil "Symbola" nil 'append)
#+end_src
** Syne
Typeface designed for the Synesthésie art center in Saint-Denis suburb of Paris ([[https://www.lucasdescroix.fr/words/atypical-gathering][link]], [[https://gitlab.com/bonjour-monde/fonderie/syne-typeface][Gitlab]]).
It has five subfamilies with distinct styles: Extra (display), Regular (regular text), Bold (bold text), Italic (handwritten look) and Mono (distorted look).
* Links
- [[https://aplwiki.com/wiki/Fonts][APL Fonts]]
- [[https://beautifulwebtype.com/][Beautiful Web Type]]
- [[https://coding-fonts.css-tricks.com/][Coding Fonts]]
- [[https://devfonts.gafi.dev/][Dev Fonts]]
- [[https://www.huertatipografica.com/en][Huerta Tipográfica]]
- [[https://open-foundry.com/fonts][Open Foundry]]
- [[http://luc.devroye.org/fonts.html][On snot and fonts / Luc Devroye]]
- [[https://www.theleagueofmoveabletype.com/][The League of Moveable Type – the first open-source font foundry]] ([[https://github.com/theleagueof][Github]])
- [[https://velvetyne.fr/][Velvetyne]]
