# ~/.config/helix/config.toml - Helix configuration

[editor]
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "all"

[keys.normal]
C-o = ":config-open"
C-r = ":config-reload"
X = "extend_line_above"
# Vim-alike
D = ["extend_to_line_end", "delete_selection"]
V = ["select_mode", "extend_to_line_bounds"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

[keys.select]
# Vim-alike
D = ["extend_to_line_end", "delete_selection", "normal_mode"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
