#+TITLE: Org-Gantt example

#+LATEX_HEADER: \usepackage{pgfgantt}
#+LATEX_HEADER: \usepackage{pdflscape}

* Task Specification

Description of Project. Export to PDF via LaTeX using "~C-c C-e l o~".

Since the subtree below has the ~COMMENT~ state, it is not exported. To also export it, remove the ~COMMENT~ state before exporting.

** COMMENT Project
   :PROPERTIES:
   :ID:       project
   :END:
*** Task 1
    SCHEDULED: <2015-05-25 Mon> DEADLINE: <2015-05-28 Thu>
    :PROPERTIES:
    :LINKED-TO: task2,task4
    :END:
*** Task 2
    :PROPERTIES:
    :ID:       task2
    :Effort:   2d
    :END:
*** Task 3
    :PROPERTIES:
    :ID:       task3
    :ORDERED:  t
    :Effort:   7d
    :END:
**** Task 3.1
     :PROPERTIES:
     :Effort:   3d
     :END:
**** Task 3.2
     :PROPERTIES:
     :Effort:   4d
     :END:
*** Task 4
    :PROPERTIES:
    :ID:       task4
    :Effort:   5d
    :LINKED-TO: task3
    :END:

* Gantt chart

Press "~C-c C-x C-u~" to populate the dynamic block below before exporting to LaTeX.

 #+LATEX: \begin{landscape}
 #+BEGIN: org-gantt-chart :id "project"
 \begin{ganttchart}[time slot format=isodate, vgrid={*4{dashed},*3{black}}]{2015-05-25}{2015-06-29}
 \gantttitlecalendar{year, month=name, day}\\
 \ganttgroup[group left shift=0.0, group right shift=-0.0, name=project]{Project}{2015-05-25}{2015-05-28}\\
   \ganttbar[bar left shift=0.0, bar right shift=-0.0, name=uniqueid1]{Task 1}{2015-05-25}{2015-05-28}\\
   \ganttbar[bar left shift=0.0, bar right shift=-0.0, name=task2]{Task 2}{2015-05-29}{2015-06-08}\\
   \ganttgroup[group left shift=0.0, group right shift=-0.0, name=task3]{Task 3}{2015-06-12}{2015-06-29}\\
     \ganttbar[bar left shift=0.0, bar right shift=-0.0, name=uniqueid2]{Task 3.1}{2015-06-12}{2015-06-23}\\
     \ganttlinkedbar[bar left shift=0.0, bar right shift=-0.0, name=uniqueid3]{Task 3.2}{2015-06-17}{2015-06-29}\\
   \ganttbar[bar left shift=0.0, bar right shift=-0.0, name=task4]{Task 4}{2015-05-29}{2015-06-11}
 \ganttlink{uniqueid1}{task2}
 \ganttlink{uniqueid1}{task4}
 \ganttlink{task4}{task3}
 \end{ganttchart}
 #+END:
 #+LATEX: \end{landscape}
